model = "gpt-5.2-codex"
model_provider = "openai"
model_reasoning_effort = "medium"
model_reasoning_summary = "detailed"
model_verbosity = "high"
model_supports_reasoning_summaries = true
approval_policy = "never"
sandbox_mode = "danger-full-access"
hide_agent_reasoning = false
file_opener = "none"

[features]
apply_patch_freeform = true
skills = true
tui2 = true
unified_exec = true
view_image_tool = true
web_search_request = true

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true

[mcp_servers.chrome-devtools]
command = "bunx"
args = ["-y", "chrome-devtools-mcp@latest"]

[mcp_servers.figma]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
