preferred_auth_method = "chatgpt"
model = "gpt-5.1-codex-max"
model_provider = "openai"
model_reasoning_effort = "medium"
model_verbosity = "high"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
disable_response_storage = true
hide_agent_reasoning = false
file_opener = "none"

[features]
rmcp_client = true
web_search_request = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.chrome-devtools]
command = "dx"
args = ["-y", "chrome-devtools-mcp@latest"]

[mcp_servers.figma]
url = "http://127.0.0.1:3845/mcp"
