#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[settings]
activate_aggressive = true
color_theme = "catppuccin"
experimental = true
trusted_config_paths = ["~/ghq/github.com"]
install_before = "1d"
pin = true
lockfile = true
task.monorepo_depth = 2
cargo.binstall = true
npm.package_manager = "bun"
pipx.uvx = true

[tools]
node = "24.12.0"
deno = "2.6.3"
bun = "1.3.3"
rust = "1.92.0"
go = "1.25.4"
uv = "0.9.18"
shellcheck = "0.11.0"
shfmt = "3.12.0"
xcodes = "1.6.2"
bat = "0.26.1"
jq = "1.8.1"
peco = "0.5.11"
ripgrep = "15.1.0"
gh = "2.83.2"
ghq = "1.8.0"
lazygit = "0.57.0"
1password = "2.32.0"
aws-cli = { version = "2.32.25", symlink_bins = "true" }
gcloud = "550.0.0"
opencode = "1.0.207"
codex = "0.77.0"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.4"
"pipx:pfnet/plamo-translate-cli" = { version = "1.0.5", uvx_args = "-p 3.12" }
