#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[settings]
activate_aggressive = true
color_theme = "catppuccin"
experimental = true
trusted_config_paths = ["~/ghq/github.com"]
install_before = "1d"
pin = true
lockfile = true
task.monorepo_depth = 2
cargo.binstall = true
npm.package_manager = "bun"
pipx.uvx = true

# For Renovate:
# - Use short names if available (node, aws-cli), otherwise full names (aqua:peco/peco, npm:sfw)
#   https://docs.renovatebot.com/modules/manager/mise/#supported-default-registry-tool-short-names
#   https://mise.jdx.dev/registry.html#tools
# - Specify versions ("1.2.3") if Renovate recognizes them, otherwise "latest"
#   https://docs.renovatebot.com/modules/manager/mise/#limitations
[tools]
node = "24.12.0"
deno = "2.6.3"
bun = "1.3.3"
rust = "1.92.0"
go = "1.25.4"
uv = "0.9.21"
shellcheck = "0.11.0"
shfmt = "3.12.0"
jq = "1.8.1"
aws-cli = { version = "2.32.26", symlink_bins = "true" }
"aqua:XcodesOrg/xcodes" = "1.6.2"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:peco/peco" = "0.5.11"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:cli/cli" = "2.83.2"
"aqua:x-motemen/ghq" = "1.8.0"
"aqua:jesseduffield/lazygit" = "0.57.0"
"aqua:sst/opencode" = "1.0.223"
"aqua:openai/codex" = "0.77.0"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.4"
"pipx:pfnet/plamo-translate-cli" = { version = "1.0.5", uvx_args = "-p 3.12" }
"vfox:mise-plugins/vfox-1password" = "latest"
"vfox:h3y6e/vfox-gcloud" = "latest"  # https://github.com/mise-plugins/vfox-gcloud/pull/2
