#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[settings]
activate_aggressive = true
color_theme = "catppuccin"
experimental = true
trusted_config_paths = ["~/ghq/github.com"]
pin = true
cargo.binstall = true
npm.package_manager = "bun"
pipx.uvx = true
task.monorepo_depth = 2

[tools]
node = "24.12.0"
deno = "2.6.3"
bun = "1.3.3"
rust = "1.92.0"
go = "1.25.4"
uv = "0.9.18"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.4"
"pipx:pfnet/plamo-translate-cli" = { version = "1.0.5", uvx_args = "-p 3.12" }
shellcheck = "0.11.0"
shfmt = "3.12.0"
xcodes = "1.6.2"
