#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[settings]
activate_aggressive = true
experimental = true
idiomatic_version_file_enable_tools = ["node"]
trusted_config_paths = ["~/ghq/github.com/h3y6e"]
cargo.binstall = true
npm.bun = true
pipx.uvx = true

[tools]
deno = "latest"
node = "latest"
bun = "latest"
rust = "latest"
go = "latest"
uv = "latest"
"npm:npm-check" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"pipx:pfnet/plamo-translate-cli" = { version = "latest", uvx_args = "-p 3.12" }
