#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[settings]
activate_aggressive = true
color_theme = "catppuccin"
experimental = true
trusted_config_paths = ["~/ghq/github.com"]
install_before = "12h"
pin = true
lockfile = true
task.monorepo_depth = 2
cargo.binstall = true
npm.package_manager = "bun"
pipx.uvx = true

# For Renovate:
# - Use short names if available (node, aws-cli), otherwise full names (aqua:peco/peco, npm:sfw)
#   https://docs.renovatebot.com/modules/manager/mise/#supported-default-registry-tool-short-names
#   https://mise.jdx.dev/registry.html#tools
# - Specify versions ("1.2.3") if Renovate recognizes them, otherwise "latest"
#   https://docs.renovatebot.com/modules/manager/mise/#limitations
[tools]
node = "24.13.0"
deno = "2.6.8"
bun = "1.3.5"
rust = "1.93.0"
go = "1.25.4"
uv = "0.10.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"
jq = "1.8.1"
yq = "4.52.2"
aws-cli = { version = "2.33.14", symlink_bins = "true" }
"aqua:ByteNess/aws-vault" = "7.9.3"
"aqua:rhysd/actionlint" = "1.7.10"
"aqua:XcodesOrg/xcodes" = "1.6.2"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:peco/peco" = "0.5.11"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:cli/cli" = "2.86.0"
"aqua:x-motemen/ghq" = "1.8.1"
"aqua:jesseduffield/lazygit" = "0.58.1"
"aqua:anomalyco/opencode" = "1.1.53"
"aqua:openai/codex" = "latest"
"go:github.com/k1LoW/git-wt" = "0.18.0"
"npm:@sourcegraph/amp" = "latest"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.4"
"pipx:pfnet/plamo-translate-cli" = { version = "1.0.5", uvx_args = "-p 3.12" }
"vfox:mise-plugins/vfox-1password" = "latest"
