#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[settings]
activate_aggressive = true
experimental = true
idiomatic_version_file_enable_tools = ["node"]
trusted_config_paths = ["~/ghq/github.com/h3y6e"]
cargo.binstall = true
npm.bun = true
pipx.uvx = true

[tools]
deno = "2.6.1"
node = "24.11.1"
bun = "1.3.3"
rust = "1.91.1"
go = "1.25.4"
uv = "0.9.18"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.4"
"pipx:pfnet/plamo-translate-cli" = { version = "1.0.5", uvx_args = "-p 3.12" }

[hooks]
postinstall = """
deno x --install-alias
"""
